### ISSUE TITLE
Create logo and tag line for the website.

### ISSUE THREAD

**Issue by knighthood-18** [aditii-18/E-Commerce-Website#5]
A nice relevant logo and a suitable tag line for an eCommerce website.

**Comment by PaolaDaft** [comment]
I can help you with this. Any special colors you want or something special for the logo?

**Comment by knighthood-18** [comment]
Any colors that will suit the dark mode of the website as well.

**Comment by PaolaDaft** [comment]
I already have 3 ideas for the logo but I have some doubts:
1.- Do you want me to add all proposals to my PR?
2.- In which folder should I add the logos?
3.- Does the site already have a name?, because looking for it I have only seen that it's called "E-COMMERCE WEBSITE", I don't know if I should include that name in the logo or omit the name and in a future contribution add it with a name. 👀

**Comment by knighthood-18** [comment]
Add your images in the folder named as "img".
Yes, this website is named as "ShopLane", but the logo can be independent of it. Anything that you find more suitable will work.
